package com.webuitests.pages;


import com.webuiframework.oua.uitests.control.Button;
import com.webuiframework.oua.uitests.control.Element;
import com.webuiframework.oua.uitests.control.Elements;
import com.webuiframework.oua.uitests.control.Input;
import com.webuiframework.oua.uitests.control.Label;
import com.webuiframework.oua.uitests.control.Select;
import com.webuiframework.oua.uitests.panel.BasePanel;

public class LABPage extends BasePanel<LABPage>{

	private static LABPage lABPage;
	
	public static String createnewactivitybuttonXpath = "//button[contains(@class,'btn btn-primary btn-create-activity')]";	
	public static String menuXpath ="//i[contains(@class,'fa fa-bars')]";
	public static String latestActivityXpath = "//header[contains(@class,'activity-header')]/h2";
	public static String dashBoardXpath = "//span[contains(@bo-text,'item.title')]";
	public static String newActivitydashBoardXpath ="//a[contains(@ng-href,'/lab/#/')]";
	public static String settingsXpath ="//a[contains(@ng-href,'#/settings/classifications')]";
	public static String savedXpath = "//div[contains(@class,'grid-wrapper')]/descendant::*/div[@class='activity-name']/a";
	public static String addbttonXpath = "//button[contains(@class,'action-button')]";
	public static String addtopicXpath = "//li[contains(@title,'Add New Topic')]";
	public static String newTopicXpath = "//div[contains(@ng-model,'component.title')]";
	public static String saveTopicXpath =  "//button[contains(@ng-click, 'save()')]";
	public static String saveMessageXpath =  "//strong[contains(@class, 'message ng-binding')]";
	public static String addPageXpath =  "//li[contains(@title,'Add New Page')]";
	public static String addParagraphXpath = "//div[contains(@ng-model,'component.title')]";
	public static String addVideoXpath = "//li[contains(@title,'Add New Video')]";
	public static String addVideoURLXpath = "//input[contains(@placeholder,'Click to add url')]";
	public static String activityPageXpath  = "//div[contains(@class,'activity-nav')]";
	public static String settingsPageElementsXpath = "//div[contains(@class,'content-container')]/descendant::*";
	public static String settingsPageHeaderXpath ="//div[contains(@class,'top-content')]/span";
	public static String settingssidemenuXpath = "//nav[contains(@class,'side-bar-scroller')]/ul/li/a/i";
	public static String trainigpointTableElementsXpath = "//table[contains(@class,'input-table')]/tbody/tr/td/input";
	public static String addtrainingpointXpath = "//a[contains(@class,'btn-inline-add')]";
	public static String newtrainingpointXpath = "//input[contains(@class,'empty')]";
	public static String searchtrainingPointXpath = "//input[@placeholder='search']";
	public static String addedsucessfullynotificationMessageXpath = "//strong[contains(@class, 'message ng-binding')]";
	public static String trainingpointssidepaneXpath = "//a[@href='#/settings/training-points']";
	public static String tabsforcourseXpath = "//ul[contains(@class,'nav-tabs')]/li";
	public static String previewcourseXpath = "//i[contains(@class,'fa-play')]";
	public static String backToEditinpreviewXpath = "//a[contains(@class,'selected')]";
	public static String backtoeditlinkbuttoninpreviewxpath = "//a[contains(@ng-click,'backToEdit')]";
	public static String previousbuttoninpreviewXpath = "//a[contains(@ng-click,'preview.previous')]";
	public static String nextbuttoninpreviewCSS = "div.navigation-buttons > a[ng-click='preview.next()']";
	public static String finishbuttoninpreviewxpath = "//a[contains(@ng-click,'preview.finish')]";
	public static String begincourseinpreviewxpath = "//button[contains(@class,'btn-primary')]";
	public static String topicnameinoptionstabXpath = "//h2";
	public static String topicnameinpreviewXpath = "//h2";
	public static String hideOptionsXpath = "//label[text()='%s']/../descendant::*/span[contains(@class,'switch-handle')]";
	public static String hidenavigationcheckboxXpath = "//label[text()='Hide Navigation']/../descendant::*/input";
	public static String hidecheckboxXpath = "//label[text()='Hide']/../descendant::*/span[contains(@class,'switch-handle')]";
	public static String topicnameincourseXpath = "//h2/div";
	public static String coursetreecomponentsXpath = "//li[contains(@class,'tree-item')]/a";
	public static String activityNameineditXpath = "//h3";
	public static String expancomponentXpath = "//a[@title='expand or minimise']/i[contains(@class,'fa-chevron-down')]";
	public static String completeconditionid = "completionCondition";
	public static String ackledgementTextid = "acknowledgementText";
	public static String topicnameHeaderinpreviewxpath = "//h1/span";
	public static String acklodgementLabelinpreviewXpath = "//div[@class='acknowledge']/label";
	public static String acklodgementcheckboxinpreviewXpath = "//div[@class='acknowledge']/input";
	public static String vedioURLXpath = "//input[contains(@ng-change,'changeUrl()')]";
	public static String videoebdedinpreviewXpath = "//body/div[@id='player']/embed";
	public static String youtubeframeinpreviewXpath = "//div[contains(@class,'embed-responsive')]/iframe";
	public static String questionstypeOptionsXpath = "//ul[contains(@class,'square-icon-menu')]/li[contains(@ng-class,'component.questionType')]/span";
	public static String questiontypebuttonXpath = "//div[contains(@class,'select-question-type')]/a/i";
	public static String questiontoenterXpath = "//h2/div";
	public static String deletelinksforanswersXpath = "//ul[contains(@class,'answers')]/li/a[contains(@class,'delete-link')]";
	public static String addanswerXpath = "//div[contains(@class,'answer-add')]/a";
	public static String questionseditableTextboxXpath = "//ul[contains(@class,'answers')]/li/div[contains(@class,'inline-editable')]";
	public static String submitanswerXpath = "//button[contains(@class,'btn-publish')]";
	public static String questionorderingfieldXpath = "//select[contains(@ng-model,'component.questionOrdering')]";
	public static String passscoreXpath = "//div[@ng-show='component.resultsShowTotalScore']";
	public static String questioninresultsummarypageXpath = "//div[contains(@class,'assessment-result-questions')]/descendant::*/div[contains(@class,'question') and not(contains(@class,'question-text'))]";
	public static String passpercentageXpath = "//table[contains(@class,'scale')]/descendant::*/span";
	public static String labassessmentXpath = "//li[contains(@class,'tree-item ng-scope ng-pristine ng-valid assessment image-right ui-sortable-handle')]/a/span[@class='component-title ng-binding']";
	public static String navigatetoquestionXpath = "//a[contains(@ng-click,'preview.next()')]";
	public static String restartassessmentXpath = "//div[contains(@class,'redo btn btn-disabled-white btn-small')]";
	public static String devicesXpath = "//div[contains(@class,'top-content custom-branding-bg-color')]/a/i";
	public static String coursequestionXpath = "//ol[contains(@parent-type,'ASSESSMENT')]/../descendant::*/a[@ng-class='{open: component.open}']";
	public static String assessmetsoptionsXpath = "//ul[@class='nav nav-tabs']/li/a";
	public static String passscorechangeXpath = "//div[@class='pass-score']/input";
	public static String noofquestionsaskedXpath = "//input [contains(@ng-model,'component.questionsAsked')]";
	public static String passscoredisplayXpath = "//span[contains(text(),'PASS')]";
	public static String previewassessmenttitleXpath = "//h1/span";
	public static String allowskipquestionXpath = "//label[text()='Allow Skip Question']/../descendant::*/span[contains(@class,'switch-handle')]";
	public static String cannotprogressXpath = "//label[contains(text(),' progress until answered correctly')]/../descendant::*/span[contains(@class,'switch-handle')]";
	public static String skipquestionXpath = "//a[text()='Skip Question']";
	public static String previewassessmentXpath = "//e3-jplayer-wrap[contains(@mode,'PREVIEW')]/../div/h1";
	public static String previewnextquestionXpath = "//div[contains(@class,'question-playback ng-scope')]/h2";
	public static String showresultssummarypageXpath = "//label[(text()='%s')]/../descendant::*/span[contains(@class,'switch-handle')]";
	public static String assessmentsummaryprogressbarXpath = "//div[contains(@class,'progress-bar progress-bar-success')]";
	public static String noofquestionsXpath = "//div[contains(@class,'panel-heading')]/h4/a";
	public static String progressbarXpath = "//div[contains(@class,'progress-bar progress-bar-success')]/span";
	public static String dropdowncontrolforQuestionXpath = "//a[contains(@title,'%s')]/descendant::*/i";
	public static String dropdownvaluesforquestionXpath = "//a[contains(@title,'%s')]/descendant::*/ul/li/a";
	public static String passandFailtextXpath = "//label[text()='%s']/../textarea";
	public static String pagetitlesinpreviewindexXpath = "//a[contains(@class,'page-title')]";
	public static String publishbuttonXpath = "//button[contains(@class,'btn btn-publish ng-isolate-scope')]";
	public static String warningmesagebuttonsXpath = "//div[contains(@class,'modal-footer ng-scope')]/button";
	public static String publishwarningmessageXpath = "//div[contains(@class,'modal-body ng-scope')]";
	public static String warningmesageXpath = "//button[(text()='%s')]";
	public static String validatepublishXpath = "//div[contains(@class,'activity-title')]";
	public static String questionslinkinsummarypageXpath = "//div[contains(@class,'assessment-result-questions')]/descendant::*/div[contains(@class,'question') and not(contains(@class,'question-text'))]/descendant::*/span";
	public static String questiondisplayXpath = "//label[text()='Question Display']/../select";
	public static String questiondisplayOrderingXpath = "//label[text()='Question Display Ordering']/../select";
	public static String questiondisplayOrderXpath = "//label[text()='Question Display Order']/../select";
	public static String questionincourseXpath = "//a[contains(@title,'%s')]";
	public static String questionsdisplayedinsummarypage = "//h4[contains(@class,'panel-title')]/a/span";
	public static String passorfailtextXpath = "//div[@class='message']/p";
	public static String traininghoursXpath = "//span[@class='manual-duration']/label/input";
	public static String trainingpointsXpath = "//div[@class='training-point']/input";
	public static String optionsXpath = "//li[@class='tab ng-isolate-scope']/a[text()='%s']";
	public static String completionconditionXpath = "//select[contains(@ng-model,'activity.metaData.completionCondition')]";
	public static String completionconditionoptionsXpath = "//option[text()='%s']";
	
	public final Element<LABPage> menu = new Element<LABPage>("element", menuXpath,"xpath", this);
	public final Elements<LABPage> dashBoard = new Elements<LABPage>("elements", dashBoardXpath,"xpath", this);
	public final Button<LABPage> activityButton = new Button<LABPage>("button", createnewactivitybuttonXpath,"xpath", this);
	public final Elements<LABPage> savedActivity = new Elements<LABPage>("elements", savedXpath,"xpath", this);
	public final Element<LABPage> latestActivity = new Element<LABPage>("element", latestActivityXpath,"xpath", this);
	public final Element<LABPage> newActivitydashBoard = new Element<LABPage>("element", newActivitydashBoardXpath,"xpath", this);
	public final Element<LABPage> seetingsMenu = new Element<LABPage>("element", settingsXpath,"xpath", this);
	public final Button<LABPage> addbtton = new Button<LABPage>("button", addbttonXpath,"xpath", this);
	public final Element<LABPage> addtopic = new Element<LABPage>("element", addtopicXpath,"xpath", this);
	public final Input<LABPage> newTopic = new Input<LABPage>("input", newTopicXpath,"xpath", this);
	public final Button<LABPage> saveTopic = new Button<LABPage>("button", saveTopicXpath,"xpath", this);
	public final Label<LABPage> saveMessage = new Label<LABPage>("label", saveMessageXpath,"xpath", this);
	public final Element<LABPage> addPage = new Element<LABPage>("element", addPageXpath,"xpath", this);
	public final Input<LABPage> addParagraph = new Input<LABPage>("input", addParagraphXpath,"xpath", this);
	public final Element<LABPage> addVideo = new Element<LABPage>("element",addVideoXpath,"xpath", this);
	public final Input<LABPage> addVideoURL = new Input<LABPage>("input",addVideoURLXpath,"xpath", this);
	public final Element<LABPage> activityPage = new Element<LABPage>("class",activityPageXpath,"xpath", this);
	public final Elements<LABPage> SettingsPageElements = new Elements<LABPage>("class",settingsPageElementsXpath,"xpath", this);
	public final Element<LABPage> SettingsPageHeader = new Element<LABPage>("class",settingsPageHeaderXpath,"xpath", this);
	public final Elements<LABPage> SettingsSideMenuItems = new Elements<LABPage>("class",settingssidemenuXpath,"xpath", this);
	public final Elements<LABPage> TrainingTablePoint = new Elements<LABPage>("class",trainigpointTableElementsXpath,"xpath", this);
	public final Element<LABPage> TrainingPoint = new Element<LABPage>("class",trainingpointssidepaneXpath,"xpath", this);
	public final Input<LABPage> AddTrainigPoint = new Input<LABPage>("achor",addtrainingpointXpath,"xpath", this);
	public final Input<LABPage> NewTrainingPoint = new Input<LABPage>("achor",newtrainingpointXpath,"xpath", this);
	public final Input<LABPage> SearchTrainingPoint = new Input<LABPage>("achor",searchtrainingPointXpath,"xpath", this);
	public final Element<LABPage> NotificationMessage = new Element<LABPage>("achor",addedsucessfullynotificationMessageXpath,"xpath", this);
	public final Elements<LABPage> TabsForCourse = new Elements<LABPage>("achor",tabsforcourseXpath,"xpath", this);
	public final Element<LABPage> PreviewCourse = new Element<LABPage>("achor",previewcourseXpath,"xpath", this);
	public final Element<LABPage> BackToEditInPreview = new Element<LABPage>("achor",backToEditinpreviewXpath,"xpath", this);
	public final Element<LABPage> BackToEditLinkInPreview = new Element<LABPage>("achor",backtoeditlinkbuttoninpreviewxpath,"xpath", this);
	public final Element<LABPage> PreviousInPreview = new Element<LABPage>("achor",previousbuttoninpreviewXpath,"xpath", this);
	public final Element<LABPage> NextInPreview = new Element<LABPage>("achor",nextbuttoninpreviewCSS,"css", this);
	public final Element<LABPage> FinishInPreview = new Element<LABPage>("achor",finishbuttoninpreviewxpath,"xpath", this);
	public final Element<LABPage> BeginCourseInPreview = new Element<LABPage>("achor",begincourseinpreviewxpath,"xpath", this);
	public final Element<LABPage> TopicNameInPreview = new Element<LABPage>("achor",topicnameincourseXpath,"xpath", this);
	public final Elements<LABPage> ComponentsInCourseStructure = new Elements<LABPage>("achor",coursetreecomponentsXpath,"xpath", this);
	public final Element<LABPage> ActivityNameInEdit = new Element<LABPage>("label",activityNameineditXpath,"xpath", this);
	public final Element<LABPage> ExpandComponent = new Element<LABPage>("label",expancomponentXpath,"xpath", this);
	public final Select<LABPage> CompleteCondition = new Select<LABPage>("label",completeconditionid,"id", this);
	public final Input<LABPage> AcklodgementText = new Input<LABPage>("label",ackledgementTextid,"id", this);
	public final Element<LABPage> TopiHeaderInPreview = new Element<LABPage>("label",topicnameHeaderinpreviewxpath,"xpath", this);
	public final Element<LABPage> AcklodgementLabelInPreview = new Element<LABPage>("label",acklodgementLabelinpreviewXpath,"xpath", this);
	public final Element<LABPage> AcklodgementCheckboxInPreview = new Element<LABPage>("label",acklodgementcheckboxinpreviewXpath,"xpath", this);
	public final Input<LABPage> VedioURL = new Input<LABPage>("input",vedioURLXpath,"xpath", this);
	public final Element<LABPage> EmbededVideoInPreview = new Element<LABPage>("div",videoebdedinpreviewXpath,"xpath", this);
	public final Element<LABPage> YoutubeFrame = new Element<LABPage>("div",youtubeframeinpreviewXpath,"xpath", this);
	public final Elements<LABPage> QuestionsTypeOptions = new Elements<LABPage>("span",questionstypeOptionsXpath,"xpath", this);
	public final Element<LABPage> QuestionsType = new Element<LABPage>("span",questiontypebuttonXpath,"xpath", this);
	public final Input<LABPage> QuestionInputBox = new Input<LABPage>("span",questiontoenterXpath,"xpath", this);
	public final Elements<LABPage> DeleteLinksForAnswers = new Elements<LABPage>("span",deletelinksforanswersXpath,"xpath", this);
	public final Element<LABPage> AddAnswerButton = new Element<LABPage>("anchor",addanswerXpath,"xpath", this);
	public final Element<LABPage> QauestionInPreview = new Element<LABPage>("anchor",topicnameinpreviewXpath,"xpath", this);
	public final Elements<LABPage> EditableAnswerTextBox = new Elements<LABPage>("anchor",questionseditableTextboxXpath,"xpath", this);
	public final Element<LABPage> SubmitAnswerButton = new Element<LABPage>("button",submitanswerXpath,"xpath", this);
	public final Select<LABPage> QuestionOrdering = new Select<LABPage>("button",questionorderingfieldXpath,"xpath", this);
	public final Element<LABPage> PassScore = new Element<LABPage>("button",passscoreXpath,"xpath", this);
	public final Elements<LABPage> QuestionsInResultSummaryPage = new Elements<LABPage>("button",questioninresultsummarypageXpath,"xpath", this);
	public final Element<LABPage> PassPercentage = new Element<LABPage>("span",passpercentageXpath,"xpath", this);
	public final Element<LABPage> LabAssessment = new Element<LABPage>("class", labassessmentXpath,"xpath", this);
	public final Element<LABPage> NavigateToQuestion= new Element<LABPage>("class",navigatetoquestionXpath,"xpath", this);
	public final Button<LABPage> RestartAssessment =  new Button<LABPage>("button",restartassessmentXpath,"xpath", this);
	public final Elements<LABPage> Devices =  new Elements<LABPage>("class",devicesXpath,"xpath", this);
	public final Elements<LABPage> CourseQuestion = new Elements<LABPage>("class",coursequestionXpath,"xpath", this);
	public final Elements<LABPage> AssessmetsOptions = new Elements<LABPage>("class",assessmetsoptionsXpath,"xpath", this);
	public final Input<LABPage> PassScoreChange = new Input<LABPage>("input",passscorechangeXpath,"xpath", this);
	public final Input<LABPage> NoofQuestionsAsked = new Input<LABPage>("input",noofquestionsaskedXpath,"xpath", this);
	public final Element<LABPage> PassScoreDisplay = new Element<LABPage>("class",passscoredisplayXpath,"xpath", this);
	public final Element<LABPage> AllowSkipQuestion = new Element<LABPage>("class",allowskipquestionXpath,"xpath", this);
	public final Element<LABPage> SkipQuestion = new Element<LABPage>("class",skipquestionXpath,"xpath", this);
	public final Element<LABPage> CannotProgress = new Element<LABPage>("class",cannotprogressXpath,"xpath", this);
	public final Element<LABPage> PreviewAssessment = new Element<LABPage>("class",previewassessmentXpath,"xpath", this);
	public final Element<LABPage> PreviewNextQuestion = new Element<LABPage>("class",previewnextquestionXpath,"xpath", this);
	public final Element<LABPage> ShowResultsSummaryPage = new Element<LABPage>("class",showresultssummarypageXpath,"xpath", this);
	public final Element<LABPage> PreviewAssessmentTitle = new Element<LABPage>("class",previewassessmenttitleXpath,"xpath", this);
	public final Element<LABPage> AssessmentSummaryProgressbar = new Element<LABPage>("class",assessmentsummaryprogressbarXpath,"xpath", this);
	public final Elements<LABPage> NoofQuestions = new Elements<LABPage>("class",noofquestionsXpath,"xpath", this);
	public final Element<LABPage> ProgressBar = new Element<LABPage>("class",progressbarXpath,"xpath", this);
	public final Elements<LABPage> PageTitlesInCourseIndexInPreview = new Elements<LABPage>("anchor",pagetitlesinpreviewindexXpath,"xpath", this);
	public final Button<LABPage> PublishButton = new Button<LABPage>("button",publishbuttonXpath,"xpath", this);
	public final Element<LABPage> PublishWarningMessage = new Element<LABPage>("class",publishwarningmessageXpath,"xpath", this);
	public final Elements<LABPage> WarningMesageButtons = new Elements<LABPage>("class",warningmesagebuttonsXpath,"xpath", this);
	public final Element<LABPage> ValidatePublish = new Element<LABPage>("class",validatepublishXpath,"xpath", this);
	public final Elements<LABPage> QuestionLinkInSummaryPage = new Elements<LABPage>("span",questionslinkinsummarypageXpath,"xpath", this);
	public final Select<LABPage> QuestionDisplay = new Select<LABPage>("select",questiondisplayXpath,"xpath", this);
	public final Select<LABPage> QuestionDisplayOrdering = new Select<LABPage>("select",questiondisplayOrderingXpath,"xpath", this);
	public final Select<LABPage> QuestionDisplayOrder = new Select<LABPage>("select",questiondisplayOrderXpath,"xpath", this);
	public final Elements<LABPage> QuestionInSummaryPage = new Elements<LABPage>("span",questionsdisplayedinsummarypage,"xpath", this);
	public final Element<LABPage> PassorFailText = new Element<LABPage>("span",passorfailtextXpath,"xpath", this);
	public final Elements<LABPage> TrainingHours = new Elements<LABPage>("span",traininghoursXpath,"xpath", this);
	public final Element<LABPage> TrainingPoints = new Element<LABPage>("span",trainingpointsXpath,"xpath", this);
	public final Element<LABPage> CompletionCondition = new Element<LABPage>("span",completionconditionXpath,"xpath", this);
	public final Element<LABPage> CompletionConditionOptions = new Element<LABPage>("span",completionconditionoptionsXpath,"xpath", this);
	
	
	 public static LABPage get() {
	        if (lABPage == null) {
	        	lABPage = new LABPage();
	        }
	        return lABPage;
	    }
}