package com.webuitests.pages;

import com.webuiframework.oua.uitests.control.Button;
import com.webuiframework.oua.uitests.control.Element;
import com.webuiframework.oua.uitests.control.Elements;
import com.webuiframework.oua.uitests.control.Input;
import com.webuiframework.oua.uitests.control.Select;
import com.webuiframework.oua.uitests.panel.BasePanel;

public class LearningActivityBuilder_DashboardPage extends BasePanel<LearningActivityBuilder_DashboardPage> {
	
	private static LearningActivityBuilder_DashboardPage LABDashboardPage;
	
	public static String LABEditPanelXpath = "//div[@class='edit-panel']";
	public static String HistroyLogPanelXpath = "//div[contains(@class,'dashboard')]/descendant::*/div[contains(@class,'history-log')]";
	public static String ActivitiesConainerXpath = "//div[contains(@class,'dashboard')]/descendant::*/div[@class='contentcontainer']/section[contains(@class,'activities')]";
	public static String TutprialsPaneXpath = "//div[contains(@class,'dashboard')]/descendant::*/div[@class='contentcontainer']/section[contains(@class,'tutorials')]";
	public static String GridorListViewXpath = "//div[contains(@class,'contentcontainer')]/descendant::*/ul";
	public static String ViewButtonXpath = "//div[contains(@class,'grid-table-view')]/a[contains(@class,'active')]";
	public static String gridOrListViewXpath = "//div[contains(@class,'grid-table-view')]/a[not(contains(@class,'active'))]/i";
	public static String activitynameXpath = "//div[contains(@class,'activity-name')]/a";
	public static String contextmenubuttonXpath = "//ul[contains(@class,'activity-grid')]/descendant::*/a[text()='%s']/../../../../descendant::*/i[contains(@class,'fa-ellipsis-v')]";
	public static String contextmenubuttononlistviewXpath = "//ul[contains(@class,'activity-table')]/descendant::*/a[text()='%s']/../../../descendant::*/a[@class='dropdown-toggle']/i";
	public static String contextmenuOptionsForactivityXpath = "//ul[contains(@class,'activity-grid')]/descendant::*/a[contains(text(),'%s')]/../../../../descendant::*/ul/li/a";
	public static String contextmenuoptioninlistviewforactivityXpath = "//a[text()='%s']/../../../descendant::*/ul/li/a";
	public static String sortOptionXpath = "//div[contains(@class,'table-controls')]/select";
	public static String activityModalDialogXpath = "//div[contains(@class,'modal-dialog')]";
	public static String activityNameThumNailXpath = "//ul[contains(@class,'activity-grid')]/descendant::*/a[text()='%s']/../../../..";
	public static String activitydescriptionInSummaryPanelXpath = "//div[contains(@ng-show,'description')]/descendant::*/p";
	public static String activitycategoryInSummaryPanelXpath = "//div[contains(@ng-show,'category')]/p";
	public static String activityproviderInSummaryPanelXpath = "//div[contains(@ng-show,'provider')]/p";
	public static String activitytraininghoursInSummaryPanelXpath = "//div[contains(@ng-show,'trainingHours')]/p";
	public static String activitycertificateInSummaryPanelXpath = "//div[contains(@ng-show,'certificate')]/p";
	public static String activitylastlogInSummaryPanelXpath = "//div[contains(@ng-show,'lastLog')]/p";
	public static String latestactivitiesheaderXpath = "//header[contains(@class,'activity-header')]";
	public static String activitiesfromHistoryLogXpath = "//div[contains(@class,'history-log')]/descendant::*/div/a";
	public static String activitiesListFromHistoryLogXpath = "//div[contains(@class,'history-log')]/descendant::*/a[contains(text(),'%s')]";
	public static String activityactionfromHistoryLogXpath = "//div[contains(@class,'history-log')]/descendant::*/a[contains(text(),'%s')]/../strong";
	public static String activitymodifiedByFromHistoryXpath = "//div[contains(@class,'history-log')]/descendant::*/a[contains(text(),'%s')]/../div/span";
	public static String vediotutorialsXpath = "//section[@class='video-tutorials']/descendant::*/a";
	public static String menulabelXpath = "//a[contains(@class,'menu-item')]/span";
	public static String menuoptionsXpath = "//span[contains(text(),'Menu')]/../../descendant::*/span[@class='ng-binding']";
	public static String inputsearchboxXpath = "//input[@type='search']";
	public static String noofsearchresultsXpath = "//li[contains(@class,'activity-row')]";
	public static String searchresultHeaderXpath = "//header[contains(@class,'activity-header')]/descendant::*/ng-pluralize";
	public static String activityTypeinSearchResultXpath = "//div[contains(@class,'activity-type ng-binding')]";
	public static String createnewactivityXpath = "//button[contains(@class,'btn-primary btn-create-activity')]";
	public static String createactivityactionbuttonsXpath = "//div[contains(@class,'editing-mode')]/div/button";
	public static String activityrowinListXpath = "//div[contains(@class,'activity-name')]/a[contains(text(),'%s')]/../../..";
	public static String pductMenubuttonXpath = "//i[contains(@class,'fa-caret-down')]";
	public static String dashbordTitleXpath = "//h1[@class='top-content-title']/span[not(contains(@class,'right ng-binding'))]";
	public static String classificationsheaderXpath = "//h1[@class='top-content-title']";
	public static String knowledgebaseheaderXpath = "//h2/a";
	public static String knoledgebasehomeXpath = "//div[@class='Nav']/descendant::*/a";
	public static String signInXpath = "//div[@class='user']/a";
	public static String searchheaderforactivitynameXpath = "//span[contains(@ng-switch-when,'search')]";
	public static String activitynameInsearchresultXpath = "//span[contains(@ng-switch-when,'search')]//strong";
	public static String activitytypeinsearchResultXpath = "//div[contains(@class,'activity-type ng-binding')]";
	public static String newactivitysectionXpath = "//h3/a";
	public static String informationmessageXpath = "//div[contains(@class,'latest-message')]";
	public static String newactivityTabXpath = "//ul[contains(@class,'nav-tabs')]/descendant::*/a";
	public static String addcomponentsectionXpath = "//div[contains(@class,'component-dropdown')]";
	public static String newactivityactionbuttonXpath = "//div[contains(@class,'top-content ')]/a[contains(@class,'action-button')]";
	public static String addcomponentXpath = "//div[contains(@class,'component-dropdown')]/button/i";
	public static String addcomponentsXpath = "//ul[contains(@class,'add-component-nav')]/descendant::*/span";
	public static String closeactivityXpath = "//a[contains(@class,'close-activity')]/i";
	public static String activityNameonEditXpath = "//h3/a";
	public static String activitystatusXpath = "//ul[contains(@class,'activity-grid')]/descendant::*/a[text()='%s']/../../../div[contains(@class,'activity-status')]";
	public static String vediopagetitleXpath = "//h2[@id='title']";
	public static String activitytypeXpath = "//ul[contains(@class,'activity-grid')]/descendant::*/a[text()='%s']/../../../div[contains(@class,'activity-type')]";
	public static String activityunitIdXpath = "//ul[contains(@class,'activity-grid')]/descendant::*/a[text()='%s']/../../../descendant::*/span[contains(@class,'unit')]";
	public static String activityDescriptionXpath = "//ul[contains(@class,'activity-grid')]/descendant::*/a[text()='%s']/../../../../descendant::*/p";
	public static String activitytitleinpreviewXpath = "//div[contains(@class,'activity-title')]/h1";
	public static String beginCoursebuttonXpath = "//button[contains(@class,'btn-primary')]";
	public static String warningmessageXpath = "//div[contains(@class,'modal-content')]//div[contains(@class,'modal-body')]";
	public static String buttononwarningmessageXpath = "//div[contains(@class,'modal-content')]//div[contains(@class,'modal-footer')]/button";
	public static String userdetailsXpath = "//i[contains(@ng-if,'menu.avatar')]";
	public static String userprofileactionXpath = "//ul[contains(@class,'profile-dropdown')]/li";
	public static String HistorylogdetailsXpath = "//div[contains(@class,'history-log')]/descendant::*/a[text()='%s']/../div";
	public static String HistoryactivitynameXpath = "//div[contains(@class,'history-log')]/descendant::*/a[text()='%s']/../a";
	public static String HistoryactivitynameactionXpath = "//div[contains(@class,'history-log')]/descendant::*/a[text()='%s']/../strong";
	public static String addcomponentactionbuttonXpath = "//button[contains(@class,'action-button')]/i";
	public static String learningactivitybuildercomponentsXpath = "//ul[contains(@class,'add-component-nav')]/descendant::*/span";
	public static String activityStatusInPreviewXpath = "//div[contains(@class,'activity-status')]/p";
	public static String componentsInpreviewXpath = "//ol[contains(@class,'components-titles')]/descendant::*/a";
	public static String dashboardactivityXpath ="//ul[contains(@class,'activity-grid')]/descendant::*/div[contains(@class,'activity-status')]/../descendant::*/a[text()='%s']";
	
	public final Element<LearningActivityBuilder_DashboardPage> HistroyLogPanel = new Element<LearningActivityBuilder_DashboardPage>("panel", HistroyLogPanelXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivitiesPanel = new Element<LearningActivityBuilder_DashboardPage>("panel", ActivitiesConainerXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> TutorialPanel = new Element<LearningActivityBuilder_DashboardPage>("panel", TutprialsPaneXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> View = new Elements<LearningActivityBuilder_DashboardPage>("panel", GridorListViewXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> GirdOrListView = new Element<LearningActivityBuilder_DashboardPage>("button", gridOrListViewXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ViewButton = new Element<LearningActivityBuilder_DashboardPage>("panel", ViewButtonXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> ActivityTitles = new Elements<LearningActivityBuilder_DashboardPage>("panel", activitynameXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> contextMenuOptions = new Elements<LearningActivityBuilder_DashboardPage>("panel", contextmenuOptionsForactivityXpath,"xpath", this);
	public final Select<LearningActivityBuilder_DashboardPage> SortOptions = new Select<LearningActivityBuilder_DashboardPage>("Select", sortOptionXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityModalDialog = new Element<LearningActivityBuilder_DashboardPage>("dialog", activityModalDialogXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityDescriptionInSummaryPane = new Element<LearningActivityBuilder_DashboardPage>("label", activitydescriptionInSummaryPanelXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityCategoryInSummaryPane = new Element<LearningActivityBuilder_DashboardPage>("label", activitycategoryInSummaryPanelXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityProviderInSummaryPane = new Element<LearningActivityBuilder_DashboardPage>("label", activityproviderInSummaryPanelXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityTrainingHoursInSummaryPane = new Element<LearningActivityBuilder_DashboardPage>("label", activitytraininghoursInSummaryPanelXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityCertificateInSummaryPane = new Element<LearningActivityBuilder_DashboardPage>("label", activitycertificateInSummaryPanelXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityLastLogInSummaryPane = new Element<LearningActivityBuilder_DashboardPage>("label", activitylastlogInSummaryPanelXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> LatestActivityHeader = new Element<LearningActivityBuilder_DashboardPage>("label", latestactivitiesheaderXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> ActivitiesFromHistoryLog = new Elements<LearningActivityBuilder_DashboardPage>("label", activitiesfromHistoryLogXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> VedioTutorials = new Elements<LearningActivityBuilder_DashboardPage>("label", vediotutorialsXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> MenuOptions = new Elements<LearningActivityBuilder_DashboardPage>("label", menulabelXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> MenuDropdownOptions = new Elements<LearningActivityBuilder_DashboardPage>("label", menuoptionsXpath,"xpath", this);
	public final Input<LearningActivityBuilder_DashboardPage> SearchBox = new Input<LearningActivityBuilder_DashboardPage>("input", inputsearchboxXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> SearchResults = new Elements<LearningActivityBuilder_DashboardPage>("list", noofsearchresultsXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> SearchResultHeader = new Element<LearningActivityBuilder_DashboardPage>("label", searchresultHeaderXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> ActivityType = new Elements<LearningActivityBuilder_DashboardPage>("label", activityTypeinSearchResultXpath,"xpath", this);
	public final Button<LearningActivityBuilder_DashboardPage> CreateNewActivityButton = new Button<LearningActivityBuilder_DashboardPage>("input", createnewactivityXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> SaveAndPublishButtons = new Elements<LearningActivityBuilder_DashboardPage>("Buttons", createactivityactionbuttonsXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ProductMenuButton = new Element<LearningActivityBuilder_DashboardPage>("label", pductMenubuttonXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> DashBoardTitle = new Element<LearningActivityBuilder_DashboardPage>("header", dashbordTitleXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ClassificationHeader = new Element<LearningActivityBuilder_DashboardPage>("header", classificationsheaderXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> KnowledgeBaseHeader = new Element<LearningActivityBuilder_DashboardPage>("header", knowledgebaseheaderXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> KnowledgeBaseHome = new Element<LearningActivityBuilder_DashboardPage>("header", knoledgebasehomeXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> SignInLink = new Element<LearningActivityBuilder_DashboardPage>("header", signInXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> SearchHeaderForActivity = new Element<LearningActivityBuilder_DashboardPage>("header", searchheaderforactivitynameXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityNameInSearchResult = new Element<LearningActivityBuilder_DashboardPage>("header", activitynameInsearchresultXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> ActivityTypeInSearchResult = new Elements<LearningActivityBuilder_DashboardPage>("columnlabel", activitytypeinsearchResultXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> NewActivitySection = new Element<LearningActivityBuilder_DashboardPage>("columnlabel", newactivitysectionXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> InformationMessageOnNewActivity = new Element<LearningActivityBuilder_DashboardPage>("message", informationmessageXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> TabsInNewActivity = new Elements<LearningActivityBuilder_DashboardPage>("tabs", newactivityTabXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> AddComponentSection = new Element<LearningActivityBuilder_DashboardPage>("div", addcomponentsectionXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> ActionButtonsForNewActivity = new Elements<LearningActivityBuilder_DashboardPage>("anchors", newactivityactionbuttonXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> AddComponentAction = new Element<LearningActivityBuilder_DashboardPage>("button", addcomponentXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> AddComponentsForActivity = new Elements<LearningActivityBuilder_DashboardPage>("button", addcomponentsXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> CloseActivity = new Element<LearningActivityBuilder_DashboardPage>("button", closeactivityXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityNameOnEdit = new Element<LearningActivityBuilder_DashboardPage>("label", activityNameonEditXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> VedioPageTitle = new Element<LearningActivityBuilder_DashboardPage>("label", vediopagetitleXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityTitleInPreview = new Element<LearningActivityBuilder_DashboardPage>("label", activitytitleinpreviewXpath,"xpath", this);
	public final Button<LearningActivityBuilder_DashboardPage> BeginCourseButton = new Button<LearningActivityBuilder_DashboardPage>("button", beginCoursebuttonXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> WarningMessageOnDelete = new Element<LearningActivityBuilder_DashboardPage>("label", warningmessageXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> ButtonOnDeleteWarningMessage = new Elements<LearningActivityBuilder_DashboardPage>("buttons", buttononwarningmessageXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> UserDetailDropDown = new Element<LearningActivityBuilder_DashboardPage>("label", userdetailsXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> UserProfileAction = new Elements<LearningActivityBuilder_DashboardPage>("link", userprofileactionXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> AddComponentActionButton = new Element<LearningActivityBuilder_DashboardPage>("label", addcomponentactionbuttonXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> LearningActivityBuilderComponents = new Elements<LearningActivityBuilder_DashboardPage>("label", learningactivitybuildercomponentsXpath,"xpath", this);
	public final Element<LearningActivityBuilder_DashboardPage> ActivityStatusInPreview = new Element<LearningActivityBuilder_DashboardPage>("label", activityStatusInPreviewXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> ComponentsInPreview = new Elements<LearningActivityBuilder_DashboardPage>("spans", componentsInpreviewXpath,"xpath", this);
	public final Elements<LearningActivityBuilder_DashboardPage> ActivityStatus = new Elements<LearningActivityBuilder_DashboardPage>("calss", activitystatusXpath,"xpath", this);
	
	public static LearningActivityBuilder_DashboardPage get() {
        if (LABDashboardPage == null) {
        	LABDashboardPage = new LearningActivityBuilder_DashboardPage();
        }
        return LABDashboardPage;
    }

}